### ISSUE TITLE
APD Price Matrix new price 2021

### ISSUE THREAD

**Issue by SandraVeselovska** [DimitriOstapenko/OMS#31]
APD has changed prices since the new year 2021, as the attached table below. 

I have checked “price matrix”, the OMS is set up that TOPmarques and GP replica brands have the same prices for 1.18 or 1.12 scale only selected street or racing versions. 

Since the new year the company has decided to selected prices from different brands as show in the table below.  GP replica also started production with a special acrylic box but only for certain models. 

Therefore, we need to add a brand category to the price matrix so that the software can select from which cell it will be entering the price for and individual items, if I understand the system correctly. 

also all prices in backordres should be changed. 

![Screenshot 2021-01-07 at 15 51 15](https://user-images.githubusercontent.com/69158912/104501367-ea2fc800-55df-11eb-8b6c-256e3887d467.png)

![Screenshot 2021-01-07 at 15 55 42](https://user-images.githubusercontent.com/69158912/104501381-edc34f00-55df-11eb-8d37-2bad9367acda.png)

**Comment by DimitriOstapenko** [comment]
This is now complete. There's rule for each brand.
