### ISSUE TITLE
prices have not been updated

### ISSUE THREAD

**Issue by SandraVeselovska** [DimitriOstapenko/OMS#33]
After applying the new prices to all pending orders, I found that some prices had not been updated.

I checked the example of customer Kyosho. Some prices have been updated and some still have old prices.

Please find attached a file with comparison prices.

Also, I found out that models TOP100Z and TOP90C have at downloaded backorder price 129 euro but price matrix show 128.50 euro = 0.50 cents differences. 

[BO OMS KYOSHO 02.03.2021.xlsx](https://github.com/DimitriOstapenko/OMS/files/6077338/BO.OMS.KYOSHO.02.03.2021.xlsx)

**Comment by DimitriOstapenko** [comment]
There's 2 separate (non) issues here:

1. Some prices have not been updated because orders are not pending, they are actually active with some pending placements. If order is active we don't touch it
   for example order 798: GP027A : Old price because order is active

2. I took same report for KYOSHO and found out that both items you mention have actually correct prices of 128.95. It's probably your excel rounding that's not set correctly.

So I'm closing this as non issue

[2021-03-02-637.xlsx](https://github.com/DimitriOstapenko/OMS/files/6078590/2021-03-02-637.xlsx)

**Comment by DimitriOstapenko** [comment]
This is funny..  Do you know how to use Excel? 
You sheet has correct prices. Just make the column wider and you will see that it's actually 128.95, not 129.

By the way, price shown in matrix is 128.95 ( shown right in your file),  not 128.5.

**Comment by SandraVeselovska** [comment]
That is really interesting,  because other 128.95 prices are correct only these two amount have been rounded. 


Since active order can not be updated the function is useless. 


Mgr. Sandra 
sandra@ecdbv.com
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by DimitriOstapenko** [comment]
I don’t know what you did. All shows fine when I open that sheet.


Function updates pending orders only to avoid messing up active orders.
This is the only reasonable approach in my view.


--
Dmitri Ostapenko
APDOMS site admin

**Comment by SandraVeselovska** [comment]
When I open the sheet the active orders are not updated what client and APD management needed. 


Mgr. Sandra 
sandra@ecdbv.com
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by DimitriOstapenko** [comment]
If you think that all pending placements should be changed instead, I can easily do it, but that will be your responsibility


--
Dmitri Ostapenko
APDOMS site admin

**Comment by DimitriOstapenko** [comment]
Do you understand the difference between “active” and “pending”? 

And also between “order” and “placement”?

I have a feeling that you don’t.

Also, there’s no mention of need to change active orders anywhere in the list of requested changes that Max gave me.

—
Dimitri Ostapenko
APD OMS
Site Admin

**Comment by DimitriOstapenko** [comment]
Spoke with Peter and he said that we should change all pending placements, not just orders.
Appropriate modification is made and this change is now live on production server.
