### ISSUE TITLE
OMS does not respond when entering a new contact

### ISSUE THREAD

**Issue by SandraVeselovska** [DimitriOstapenko/OMS#34]
Im not able to add any client contact to the OMS. 

https://apdoms.com/clients

![Screenshot 2021-03-03 at 17 13 08](https://user-images.githubusercontent.com/69158912/109835712-c41fbf00-7c43-11eb-90a6-484179884be3.png)

**Comment by DimitriOstapenko** [comment]
FIxed

**Comment by SandraVeselovska** [comment]
Perfect thank you ! 

Mgr. Sandra 
sandra@ecdbv.com
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by SandraVeselovska** [comment]
Hello Dimitri, 

It still doest work for me. 


Mgr. Sandra 
sandra@ecdbv.com
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by DimitriOstapenko** [comment]
Wait, I have not updated the server yet. Still looking at the other issue.

Please check tomorrow.



--
Dmitri Ostapenko
APDOMS site admin

**Comment by SandraVeselovska** [comment]
Thank you I will keep you posted. 


Mgr. Sandra 
sandra@ecdbv.com
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797
