### ISSUE TITLE
Client report - client access 

### ISSUE THREAD

**Issue by SandraVeselovska** [DimitriOstapenko/OMS#36]
customers can not download their overview of orders, this option is not offered to them by OMS, before it was able. 

![Screenshot 2021-03-30 at 14 16 40](https://user-images.githubusercontent.com/69158912/112987082-9a828680-9162-11eb-8c25-8a72f1658d3c.png)

**Comment by DimitriOstapenko** [comment]
Clients can create product reports, I just verified.
If other types of reports are required, please specify which ones

**Comment by SandraVeselovska** [comment]
I already specified, before they was able to create client report, they order report, why have you change it ? 

Mgr. Sandra 
***@***.***
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by SandraVeselovska** [comment]
Anyway I told it is no longer possible. 

Is it really necessary to have quotes for the code model?




Mgr. Sandra 
***@***.***
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by SandraVeselovska** [comment]
Yes, I remember, I have requested model TOP106, but this issue is still current (attached print screen).

So based on that you have added quotes to customers' files and now they are asking us to download their backorders. 

I thought you had to simplify the software, it would probably be better if you shared the proposed solutions to really solve the issues and not complicate work employees and customers. I dont know how to explain Asian customers quotes if Asians start will fully use OMS.  

Our access 

Mgr. Sandra 
***@***.***
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by SandraVeselovska** [comment]
Hello Dimiri, 

my colleague informed me that whenever she sends orders to a customer, she must remove the quotation marks for the codes.

I would very kindly like to ask you if it would be possible to simplify our work. Orders are just a small piece that we are in charge of.
