### ISSUE TITLE
Magic Model - alarm something went wrong 

### ISSUE THREAD

**Issue by SandraVeselovska** [DimitriOstapenko/OMS#37]
Customer Magic Model wanted to place an order but after the button "Submit order " he received alarm info " something went wrong", also I tried and the same info I have received. 

![Screenshot 2021-04-09 at 15 46 14](https://user-images.githubusercontent.com/69158912/114189656-bb10c480-994a-11eb-9194-3d74bbad4285.png)

**Comment by DimitriOstapenko** [comment]
Valid issue. This is now fixed.

Thanks for letting me know. 
—
Dimitri Ostapenko
APD OMS
Site Admin

**Comment by SandraVeselovska** [comment]
Thank you
