### ISSUE TITLE
Search bar issue 

### ISSUE THREAD

**Issue by SandraVeselovska** [DimitriOstapenko/OMS#38]
The customer SASU wanted to search for products in the search bar, he choosed TOP it showed 206 results but he cannot see them in the list blow. 
I logged in to his account and it worked for everything well.

I advised him to change browser to Chrome and log out and log in again, also I requested try other pages but nothing changes. 

what should I advise to the customer ?

print screen what he sent me 

![image](https://user-images.githubusercontent.com/69158912/114190736-ed6ef180-994b-11eb-83cd-0b94b410c605.png)

**Comment by DimitriOstapenko** [comment]
Not sure. All seems fine on my end

—
Dimitri Ostapenko
APD OMS
Site Admin

**Comment by DimitriOstapenko** [comment]
Actually, he’s not registered. 


—
Dimitri Ostapenko
APD OMS
Site Admin

**Comment by SandraVeselovska** [comment]
Yes he is he is our big customer, 


Mgr. Sandra 
***@***.***
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by DimitriOstapenko** [comment]
Look at the screen I sent you

Dimitri Ostapenko
APD OMS
Site Admin

**Comment by SandraVeselovska** [comment]
very interesting that the SASU customer is not registered, he was invited to the OMS several times as we unsuccessfully had to exchange email addresses.

Please register it

**Comment by DimitriOstapenko** [comment]
He has to confirm his registration from email.

—

Dimitri Ostapenko
APD OMS
Site Admin

**Comment by SandraVeselovska** [comment]
I have informed him that he will receive an email about registration.

**Comment by ostinjim** [comment]
No he won’t. You have to invite him


Sent from Yahoo Mail for iPhone


On Friday, April 9, 2021, 16:30, SandraVeselovska ***@***.***> wrote:




I have informed him that he will receive an email about registration.

**Comment by DimitriOstapenko** [comment]
I manually fixed his record. All should work now. I was able to make test order as him, which is now deleted.


Dimitri Ostapenko
APD OMS
Site Admin

**Comment by SandraVeselovska** [comment]
Hello Dimitri, 

Thank you for registration of the SASU customer. I just received the email from Mr. Antoine and his password is invalid. Did you change the password ? Let me know or should I change the password ? 




Mgr. Sandra 
***@***.***
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by DimitriOstapenko** [comment]
Hi Sandra,

No, I did not change his password. 
He can reset it himself by using “forgot password” link on login page.

It’s better  for customers to set their own passwords. As a last resort you can set it for him.

Dimitri Ostapenko
APD OMS
Site Admin
