### ISSUE TITLE
TOPSET001 inventory 

### ISSUE THREAD

**Issue by SandraVeselovska** [DimitriOstapenko/OMS#39]
my asian collegue is trying to uplaod inventory file, but OMS shows "Products line 272: unknown product code TOPSET001" but the code is same as in the OMS then it should be known. 

Please could you help us ? 

attached excel file - converted correctly to csv. 

[Update  Stock list  17-4-2021.xlsx](https://github.com/DimitriOstapenko/OMS/files/6329051/Update.Stock.list.17-4-2021.xlsx)

![Screenshot 2021-04-17 at 12 30 42](https://user-images.githubusercontent.com/69158912/115109885-c0889300-9f78-11eb-835d-ea3160b84445.png)

**Comment by SandraVeselovska** [comment]
im sending you corect excel file, before she had freezer first row. 
attached 
[Update  Stock list  17-4-2021.xlsx](https://github.com/DimitriOstapenko/OMS/files/6329055/Update.Stock.list.17-4-2021.xlsx)

**Comment by DimitriOstapenko** [comment]
Hi Sandra,

Please provide actual CSV file you/they are trying to upload and I will take a look at it.

Thanks,
—
Dimitri Ostapenko
APD OMS
Site Admin

**Comment by DimitriOstapenko** [comment]
Ok, I found a problem "TOPSET001" had unprintable characters within it. Also, line 366 had unknown product code "TMR1204CD".  Both are fixed and file is now uploaded.

**Comment by SandraVeselovska** [comment]
Thank you Dimtiri, I will tell asian team that everything is fixed ! 


Mgr. Sandra 
***@***.***
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797
