### ISSUE TITLE
new category - ALL 

### ISSUE THREAD

**Issue by SandraVeselovska** [DimitriOstapenko/OMS#40]
I tried to download all the products from all the clients and created the file, but OMS warned me that something had gone wrong. I also tried to download pending orders from all clients and the warning reappeared. Is this feature not possible or is it just an OMS error?

https://apdoms.com/reports/new?category=1

https://apdoms.com/reports/new?category=2

![Screenshot 2021-04-20 at 12 51 08](https://user-images.githubusercontent.com/69158912/115385035-f4adbf00-a1d7-11eb-8124-b983956e9f06.png)

![Screenshot 2021-04-20 at 12 51 29](https://user-images.githubusercontent.com/69158912/115385045-f7101900-a1d7-11eb-877b-7bfba7c7e303.png)
![Screenshot 2021-04-20 at 12 51 54](https://user-images.githubusercontent.com/69158912/115385058-f9727300-a1d7-11eb-88c2-c1d64d4b23ac.png)

**Comment by DimitriOstapenko** [comment]
This is probably a bug. I will look into it tomorrow.

--
--
Dmitri Ostapenko
APDOMS site admin

**Comment by DimitriOstapenko** [comment]
Fixed

**Comment by SandraVeselovska** [comment]
Thank you ! 

Mgr. Sandra 
***@***.***
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797
