### ISSUE TITLE
Data integrity check ( prices ) 

### ISSUE THREAD

**Issue by SandraVeselovska** [DimitriOstapenko/OMS#41]
today I looked at all the shares because I need to apply a new rule since APD decided to produce car models together with figures.

Subsequently, I deleted the rule - GP replicas - Special price because we do not use the rule, let's consider that we replace the rule with models with figures, I'm waiting for Peter's decision.

When I looked at the Data integrity check, I found a lot of questions about the price. Please can you help me change what in the models, why does it show that there is a mistake?

![Screenshot 2021-05-18 at 09 46 15](https://user-images.githubusercontent.com/69158912/118612709-56a11a80-b7be-11eb-98ed-04096c34a3df.png)

**Comment by DimitriOstapenko** [comment]
Missing price rules are just that. It means that price rule is missing for given  Scale - Brand - Category. It does not necessarily mean that there are products using these rules.


--
Dmitri Ostapenko
APDOMS site admin

**Comment by SandraVeselovska** [comment]
Hi Dimitri, 

I just add missing rule for GP set, it should be fine now, and I checked other mentioned notes and its seems the items have correct prices in the price matrix. Some of them are no exist. 



 Missing Price Rules: 32 , including: | 1:8 Top Marques Set | 1:12 Top Marques Set  | 1:43 Top Marques Set | 1:8 Top Marques Special Edition
  1:12 Top Marques Special Edition | 1:43 Top Marques Special Edition | 1:8 GP Replicas Racing | 1:8 GP Replicas Street | 1:43 GP Replicas Street | 1:8 GP Replicas Set | 1:12 GP Replicas Set | 1:18 GP Replicas Set | 1:43 GP Replicas Set | 1:8 GP Replicas Special Edition | 1:12 GP Replicas Special Edition | 1:18 GP Replicas Special Edition .. | and 17 more 
 Products without matching price rule: 1 GPSET001 - I just add the rule - OK 



Mgr. Sandra 
***@***.***
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797

**Comment by DimitriOstapenko** [comment]
Hi Sandra,

I think it’s a good practice to have all the rules in place - even if prices in them are 0. This way you will see if something is wrong. The order using the product with this rule will have price of 0


--
Dmitri Ostapenko
APDOMS site admin

**Comment by SandraVeselovska** [comment]
Hi Dimitri, 

You are right, I will add other rules and then it should be correct. 

I will keep you posted. 

Mgr. Sandra 
***@***.***
European Collectible Distribution B.V.
Prinses Beatrixstraat 7
5953 LL  Reuver
The Netherlands
+3368624797
